# Build Geth in a stock Go builder container
FROM golang:1.24.2-alpine as builder

RUN apk add --no-cache make gcc g++ musl-dev linux-headers git  libstdc++

ADD . /go-ethereum
RUN cd /go-ethereum && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /go-ethereum/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 30303 30303/udp
