// Code generated by rlpgen. DO NOT EDIT.

package types

import "github.com/Project-InitVerse/chain/rlp"
import "io"

func (obj *StateAccount) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteUint64(obj.Nonce)
	if obj.Balance == nil {
		w.Write(rlp.EmptyString)
	} else {
		w.WriteUint256(obj.Balance)
	}
	if obj.LockBalance == nil {
		w.Write(rlp.EmptyString)
	} else {
		w.WriteUint256(obj.LockBalance)
	}
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.CodeHash)
	w.ListEnd(_tmp0)
	return w.Flush()
}
